#
# This helper script will install smartmontools set "smartd.conf" and configure regular testing schedule
# Will also install the nvme-cli utils for supporting NVMe devices.
#
---
- name: Install and Configure SmartMon Tools Block
  when:
    - ansible_os_family == "Debian"
  tags:
    - setup_smartmontools
  block:
    - name: Install packages
      ansible.builtin.apt:
        name: ['smartmontools', 'nvme-cli']
        state: present
        install_recommends: false
      when:
        - ansible_os_family == "Debian"

    # Remove any pre-existing devices, detected devices will be added back.
    - name: Remove existing devices from /etc/smartd.conf
      ansible.builtin.lineinfile:
        path: "/etc/smartd.conf"
        regexp: "^(\/dev\/disk\/by-id\/*)"
        state: absent

    - name: Add DEFAULT setting for all devices to /etc/smartd.conf
      ansible.builtin.lineinfile:
        path: "/etc/smartd.conf"
        regexp: "^DEFAULT"
        line: "{{ smartd_conf_values }}"
        state: present

    # Add one line per device to "/etc/smartd.conf" replace any existing line for device
    - name: Add devices to /etc/smartd.conf
      ansible.builtin.lineinfile:
        path: "/etc/smartd.conf"
        regexp: '^{{ item }}'
        line: '{{ item }} '
        state: present
      loop: "{{ disk_by_id | list }}"

    # Disable existing DEVICESCAN entry if not enabled
    - name: Disable DEVICESCAN in /etc/smartd.conf
      ansible.builtin.lineinfile:
        path: "/etc/smartd.conf"
        regexp: '(?i)^(DEVICESCAN.*)'
        line: '# \1'
        backrefs: true
        state: present

    - name: Restart smartd service
      ansible.builtin.systemd:
        name: smartd
        state: restarted
