# This script updated the default list of services hardcoded in the services MOTD file
---
- name: Update Services MOTD File Services List Block
  block:

  - name:  Combine all Services into a space delimited list of services in a string
    set_fact:
      services_list: "{{services_list|default('')}}\"{{item}}\" "
    with_items:
      - "{{ services_list_override_for_all_hosts|default([]) }}"
      - "{{ more_services_entries|default([]) }}"

  - name: Replace existing services list with custom list
    replace: 
      path: "{{motd_path}}/{{motd_service_file}}"
      regexp: '^(?m)services=.*$'
      replace: 'services=({{services_list}})'
  
  tags:
  - updated_services_motd_file