---
# manual_entries_to_hddtemp - manually add entries for which hddtemp cannot discover.
#  $ sudo hddtemp /dev/sda
#  If it shows: WARNING: Drive /dev/sda doesn't seem to have a temperature sensor.
#               /dev/sda: Samsung SSD 840 Series:  no sensor

#  This can help discover the device data field number for temperature:
#  $ sudo smartctl -a /dev/sda | grep -i temp

#  Finds: 190 Airflow_Temperature_Cel 0x0032   077   060   000    Old_age   Always       -       23

# Field 1: Use a string or regex matching the drive's display name (as reported by hddtemp output)
# Field 2: SMART data field number (190 for Samsung 840 and 860 models)
# Field 3: Drive reports temperature in unit (C or F)
# Field 4: Label string or comment you define
manual_entries_to_hddtemp:
  - '"Samsung SSD (840|860)" 190 C "Temp for Samsung SSDs"'
